### ISSUE TITLE
Support for computed properties?

### ISSUE THREAD

**Issue by Sajjon** [tarunon/Cuculus#2]
Hey! Fist of all let me say that this project is suuuuper cool! Nice vodoo black (C and Swift) magic enabling this. This is how mocking should work, and support for `struct`s is crucial.

Do you plan to add support for computed properties, which basically act like functions, from a Swift usage perspective, but without the need of calling it with `()`?

I guess **computed** properties would be easier to add support for than, **stored** properties, which also would be great, but I understand if it is trickier.

Good job!

**Comment by tarunon** [comment]
Thank you, actually, current implementation is calculated instruction pointer from closure thunk, so in this solution, we can't support computed property.

But I already find other way, that is using `dlsym` by mangled function name as a symbol name, we can get instruction pointer.  https://github.com/apple/swift/blob/master/docs/ABI/Mangling.rst
This is experiment implementation, I'm working it on `lab/mangle` branch.

**Comment by Sajjon** [comment]
Cool thanks! Care to add some tests for computed properties in that branch? :) 

https://github.com/tarunon/Cuculus/blob/e04c39c11cf149d51e0a3c8c819119726305721f/Tests/CuculusTests/CuculusTests.swift

**Comment by tarunon** [comment]
I will 😉

**Comment by tarunon** [comment]
I update all of things in my lib, and also pre release for initial version.
Could you please try it? @Sajjon 
https://github.com/tarunon/Cuculus/releases/tag/0.1.0
